### ISSUE TITLE
Build errors are swallowed

### ISSUE THREAD

**Issue by aciccarello** [dojo/cli-build-theme#10]
**Enhancement** 
Command should not swallow error output.

Package Version: v4.0.0-alpha.3

**Code**
```
> dojo build theme -n material

✖ Error: Failed to build material/index.d.ts
```

**Expected behavior:**
Build errors (such as TypeScript compilation errors) should be outputted to the console.

**Actual behavior:**
Only output says `Failed to build CSS modules`.

**Comment by aciccarello** [comment]
The error message comes from here. A workaround is to run the `tsc` command that the build tool is running.

modify tsconfig to include `include: ["src/**/*.ts"]` and `"compilerOptions": {"outDir": "dist/src" }`
run tsc with the project `npx tsc --project tsconfig.json`

https://github.com/dojo/cli-build-theme/blob/1965a18d65f58b9501a151fe754ec5138d99551f/src/main.ts#L72-L76

**Comment by agubler** [comment]
Should be resolved by https://github.com/dojo/cli-build-theme/pull/22
